version: '3.6'
## docker login docker.iscinternal.com
## Connect to SMP mirror A
## http://127.0.0.1:9092/csp/sys/UtilHome.csp
## Commands: 
# docker exec -it mirrorA iris session IRIS

services:
  mirrorA:
    container_name: mirrorA
    hostname: mirrorA
    image: docker.iscinternal.com/intersystems/iris:2019.3.0-latest
    volumes:
      - ./irisA:/ISC
      - ./:/ISC/utiles
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - IRIS_hostname=mirrorA
    ports:
      - "9092:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
    
  mirrorB:
    container_name: mirrorB
    hostname: mirrorB
    image: docker.iscinternal.com/intersystems/iris:2019.3.0-latest
    volumes:
      - ./irisB:/ISC
      - ./:/ISC/utiles
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - IRIS_hostname=mirrorB
    ports:
      - "9093:52773"
    command:
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
    